version: "3"
services:
  # Backend Service
  api-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: api-backend
    volumes:
      - ./backend:/app
    ports:
      - 8010:8080
    depends_on:
      - localstack
    env_file:
      - ./backend/.env.dev

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: wavy-frontend-app
    ports:
      - 3020:3000
    command: yarn dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - api-backend
    env_file:
      - ./frontend/.env.dev

  # LocalStack Service for AWS Emulation
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # External services
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8001:8001"
    depends_on:
      - localstack
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    init: true

  # MinIO Service for S3 Compatible Storage
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  frontend_node_modules:
  localstack_data:
  minio_data:
